# this is a print statment
print("bye world")
print("bye world")
print("bye world")
print("bye world")
print("bye world")
print("bye world")
print("bye world")
print("bye world")
print("bye world")
print("bye world")
print("bye world")
print("bye world")
print("bye world")
print("bye world")
print("bye world")
print("bye world")

